name: Docker Image CI

on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set API_BASE_URL
      run: echo ${{ env.API_BASE_URL }} > src/resource/string/api.json
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: ap-northeast-2
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set short sha
      id: sha_short
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.9.1
      with:
        platforms: linux/amd64

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build react project
      run: |
        npm ci
        npm run build
    
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr-repository
        IMAGE_TAG: dynamic
#        IMAGE_TAG: ${{ steps.sha_short.outputs.sha_short }}
      run: |
        docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push .
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
